---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

somnia:
  validator:
    source_url: gs://somnia-releases/binaries
    ports:
      protocol_port: 9000
      data_port: 9001
      api_http_port: 9002
      api_ws_port: 9003
      metrics_port: 9004
