$ANSIBLE_VAULT;1.1;AES256
39623066363538633035333731346461316533353265363237323563623565633661336439666539
3566306436633032393865643237636532613639343233370a336639656634616335333431383839
61323464346539343637393562613666343261613662653361386661336432616437643736623235
3666346539383962350a366332646161353436343366393134643161303936373366613563333463
31323237353664363936363633363834336436363061313239383537326632383630383862396161
36333138343566663463646438626632333863336335646431343339366331383738323566653338
62653037343962363261323739663831326162303731393638666539656264316439333831633234
30316637343963343563333763626131313136343461613765376438323439626262366232616531
35313566623638623365326234393262366439313334666239386330623037353062333966643638
66396135333037633634326665356266313334666165633133393230616533353037383436363431
36346462396531336337643165653739373863643661393766626439343164623962306538633832
64373839626436666462336233623863353064396262616265656538653266653138356564363963
3833
