$ANSIBLE_VAULT;1.1;AES256
36396432376363623831376666616330393765313337663739336136633031373236383936646137
6536643764313339343735376137313063376164393035620a623533633632653734326136616234
39323634653261393134313937323739616637306638333461336138366665653061343035353039
6362376530656439330a313430656234386235333035633639333263363634336533636266663530
66343630643764363238636638623334326235303331363966373530336261333866363130656634
37306433383530663838373336373334396332626132353039633939333434616338623666626331
31303937326664366639396130326362643862396636343164376635343839336630663865343839
34323838343261656265383763613164373165316664396532666161666362656264633566633735
30313263323238633564333461633437613864303431366562386435616231613730366336333164
65623734363331353639373765333338306333306561333765636531366565336234613938316438
35663936333166666265643361653431663234343063386665396233303732303635396433306563
65613066343964323161323564356331316131303831626532303331323636643732373532386663
3838
