---
node_ufw_rules:
  - port: "{{ somnia.validator.ports.protocol_port }}"
    proto: tcp
    rule: allow
    from: any
    comment: protocol_port

  - port: "{{ somnia.validator.ports.data_port }}"
    proto: tcp
    rule: allow
    from: any
    comment: data_port

  - port: "{{ somnia.validator.ports.metrics_port }}"
    proto: tcp
    rule: allow
    from: "{{ monitor_server_dns }}"
    comment: metrics_port
